name: lint_python
on:
  push:
    branches: [master]
  pull_request:
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: 3.x}
      - run: pip install --upgrade pip setuptools wheel
      - run: pip install black codespell mypy pytest six
      - run: black --check . || true
      - run: codespell || true  # --ignore-words-list="" --skip=""
      - run: pip install -e .
      - run: mypy --ignore-missing-imports . || true
      - run: mv setup.cfg setup.cfg.disabled
      - run: pytest --ignore=tests/test_client.py --ignore=tests/test_websocket_integration.py
      - run: pytest tests/test_websocket_integration.py || true  # Todo: Fix these failing tests
      - run: pytest tests/test_client.py || true  # Todo: Fix these failing tests
      - run: safety check
