name: lint_python
on:
  push:
    branches: [master]
  pull_request:
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: 3.x}
      - run: pip install --upgrade pip setuptools wheel
      - run: pip install bandit black codespell flake8 isort mypy pytest pyupgrade
      - run: bandit --recursive --skip B101,B105,B106,B110,B303,B324,B404,B603 .
      - run: black --check . || true
      - run: codespell || true  # --ignore-words-list="" --skip=""
      - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - run: flake8 . --count --exit-zero --max-complexity=29 --max-line-length=167 --show-source --statistics
      - run: isort --check-only --profile black .
      - run: pip install -e .
      - run: mypy --ignore-missing-imports . || true
      - run: pytest --ignore=tests/test_client.py --ignore=tests/test_websocket_integration.py
      - run: pytest tests/test_websocket_integration.py || true  # Todo: Fix these failing tests
      - run: pytest tests/test_client.py || true  # Todo: Fix these failing tests
      - run: shopt -s globstar && pyupgrade --py38-plus **/*.py || true
