# https://docs.astral.sh/ruff
name: ruff
on:
  push:
    branches: [master]
  pull_request:
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pip install --user ruff
    - run: ruff --output-format=github .
